//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerActions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")]
        public string App_Author {
            get {
                return ((string)(this["App_Author"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Excel-projects/Server-Help/issues/new")]
        public string App_PathNewIssue {
            get {
                return ((string)(this["App_PathNewIssue"]));
            }
            set {
                this["App_PathNewIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Excel-projects/Server-Help/blob/master/README.md")]
        public string App_PathReadMe {
            get {
                return ((string)(this["App_PathReadMe"]));
            }
            set {
                this["App_PathReadMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11/02/2018 12:00:00")]
        public global::System.DateTime App_ReleaseDate {
            get {
                return ((global::System.DateTime)(this["App_ReleaseDate"]));
            }
            set {
                this["App_ReleaseDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Results")]
        public string Ping_Results {
            get {
                return ((string)(this["Ping_Results"]));
            }
            set {
                this["Ping_Results"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dNSHostname")]
        public string Ping_ServerName {
            get {
                return ((string)(this["Ping_ServerName"]));
            }
            set {
                this["Ping_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OperatingSystem")]
        public string Rdg_Comment {
            get {
                return ((string)(this["Rdg_Comment"]));
            }
            set {
                this["Rdg_Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CN")]
        public string Rdg_Description {
            get {
                return ((string)(this["Rdg_Description"]));
            }
            set {
                this["Rdg_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\Test.rdg")]
        public string Rdg_FileName {
            get {
                return ((string)(this["Rdg_FileName"]));
            }
            set {
                this["Rdg_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDAP://OU=Servers,...")]
        public string Rdg_LdapPath {
            get {
                return ((string)(this["Rdg_LdapPath"]));
            }
            set {
                this["Rdg_LdapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT whenCreated, whenChanged, distinguishedName, OperatingSystem, OperatingSys" +
            "temVersion, dNSHostname, Name, CN FROM \'[Rdg.LdapPath]\' WHERE objectClass = \'com" +
            "puter\'")]
        public string Rdg_LdapQry {
            get {
                return ((string)(this["Rdg_LdapQry"]));
            }
            set {
                this["Rdg_LdapQry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ServerType")]
        public string Rdg_ServerGroup {
            get {
                return ((string)(this["Rdg_ServerGroup"]));
            }
            set {
                this["Rdg_ServerGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dNSHostname")]
        public string Rdg_ServerName {
            get {
                return ((string)(this["Rdg_ServerName"]));
            }
            set {
                this["Rdg_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Servers")]
        public string Rdg_SheetName {
            get {
                return ((string)(this["Rdg_SheetName"]));
            }
            set {
                this["Rdg_SheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathLocalData {
            get {
                return ((string)(this["App_PathLocalData"]));
            }
            set {
                this["App_PathLocalData"] = value;
            }
        }
    }
}
